Limit crud #18
uclibs/adopt-a-book pull request #30
Opened 2020-09-24 22:13 UTC by priyakvs

- Limited Create, Edit, Update and Delete to logged in admin Users.
- Disabled view of CRUD buttons from UI.
- Have used timeout in devise and have set that to 30 seconds for now to test which will later be 8 hours after which admin users lose their session and have to log in again to do admin related stuff.
- Have modified specs to incorporate devise and access changes. Have used FactoryBot.

So now, loggedIn admin users will see CRUD products page and general users will see just the index and show pages.

2020-09-27 18:40 UTC, hortongn requested changes
@priyakvs Please add some product view index specs that test that the `Edit`, `Destroy`, and `New product` links show when an admin is logged in and are hidden when not logged in.

2020-09-30 18:54 UTC, priyakvs commented
I have added specs to index view of products to test difference in view for logged in users.

2020-10-01 20:11 UTC, priyakvs commented
Hi Glen. I have resolved conflicts for this branch.

2020-10-01 21:07 UTC, hortongn approved these changes
@priyakvs 👍

2020-10-01 21:07 UTC, merged