Fixes #33: Created new table for adopters
uclibs/adopt-a-book pull request #37
Opened 2020-10-22 23:18 UTC by priyakvs

1. Created adopters table separately.
2. Referenced it to products table.
3. Changed forms and specs to incorporate the change.

2020-10-26 18:33 UTC, hortongn requested changes
@priyakvs Please see my comments in your PR.  Let me know if you have any questions.  Thanks!

2020-10-26 18:33 UTC, hortongn commented on db/migrate/20201022160750_create_adopters.rb
> +      t.string :adopter_fname
Please remove the `adopter_` part of the symbol from all of the fields.  It's nicer to have @adopter.fname instead of @adopter.adopter_fname (it looks strange to have (@adopter.adopter...)

2020-10-26 18:33 UTC, hortongn commented on app/views/products/show.html.erb
> -
Please keep all of the adopter fields in products show view.  Just change them to @adopter.fname, etc.

Also, in your ProductsController, go ahead and change your #show method to find the adopter:
```
def show
  @adopter = Adopter.find(@product.adopter_id)
end
```

2020-10-26 18:33 UTC, hortongn commented on app/views/products/show.html.erb
> -</p>
I think we should keep `@product.dedication` and `@product.recognition` here, correct?

2020-10-26 18:33 UTC, hortongn commented on db/migrate/20200916190306_create_products.rb
> +      t.references :adopter, foreign_key: true
This is fine for now since we are not in production yet, but typically it is bad practice to change existing migration files.  Instead of editing a migration, you should create a new migration that edits the existing table.

2020-10-27 23:40 UTC, priyakvs commented on db/migrate/20201022160750_create_adopters.rb
> +      t.string :adopter_fname
Yeah makes sense. Have removed the adopter_ part from all fields. Thanks Glen.

2020-10-27 23:42 UTC, priyakvs commented on app/views/products/show.html.erb
> -
I have shown all fields in the show method but the edit page and new page still has just the product table's attributes. I think we can get to that when we are designing admin page. Thanks for this suggestion.

2020-10-27 23:43 UTC, priyakvs commented on db/migrate/20200916190306_create_products.rb
> +      t.references :adopter, foreign_key: true
I am sorry about that Glen. Will keep in mind going forward. Thank you :)

2020-10-28 21:07 UTC, hortongn approved these changes
@priyakvs Nice job!

2020-10-28 21:07 UTC, merged