Status based product page
uclibs/adopt-a-book pull request #38
Opened 2020-10-23 05:10 UTC by priyakvs

Routes:
products/status/0: renders available books page
products/status/1: renders adopted books page

Renders available books page by default since it's the root path right now. Will change that accordingly in future since that's not required.

Wrote specs for page rendering and response for available and adopted books page

2020-10-26 21:30 UTC, hortongn requested changes
@priyakvs See my suggestion in the comments.  I'm happy to discuss if you want to talk about it.

2020-10-26 21:30 UTC, hortongn commented on app/controllers/products_controller.rb
> +                end
I think we would benefit from declaring an "enum" for the adopt_status field in the Product model.  Like this:
```
class Product < ApplicationRecord
  enum adopt_status: [:available, :adopted, :pending]
end
```

Then instead of status numbers you can use booleans like `product.adopted?` and `product.available?`.  Also, you can get all adopted product objects using `Product.adopted`.

Also, you can pass the status name in your status routes like this:
* http://localhost:3000/products/status/adopted
* http://localhost:3000/products/status/available
* http://localhost:3000/products/status/pending

So then your code above can become:
```
@products = if Product.adopt_statuses.has_key? params["status"] # security check that it's a valid param
              Product.send(params["status"])
            else
              Product.available  # if not a valid status param, just return available products
            end 
```

Read more about enums at https://www.justinweiss.com/articles/creating-easy-readable-attributes-with-activerecord-enums/

2020-10-28 02:27 UTC, priyakvs commented on app/controllers/products_controller.rb
> +                end
I have done it using enums. Thanks Glen :)

2020-10-28 21:20 UTC, hortongn approved these changes
@priyakvs 👍

2020-10-28 21:20 UTC, merged