Fix #20: Implement checkout
uclibs/adopt-a-book pull request #40
Opened 2020-11-12 19:10 UTC by priyakvs

- Implemented checkout functionality.
- Adding info to DB on click of payment.
- Specs for the same.
- Factory bots for adopter and for products with different status values.

2020-11-14 00:20 UTC, hortongn requested changes
@priyakvs Very nice.  I just have some refactoring suggestions in the comments.

2020-11-14 00:20 UTC, hortongn commented on app/controllers/cart_controller.rb
> +    Product.find(id).update(adopt_status: 0)
Because you are using enums for status, you can instead use `Product.find(id).available!` to set and save the status.  It's more readable.

2020-11-14 00:20 UTC, hortongn commented on app/controllers/application_controller.rb
> +      Product.where(id: session[:cart].keys).update_all(adopt_status: 0)
Instead of using number for the adopt_status, try this instead:
`Product.where(id: session[:cart].keys).update_all(adopt_status: Product.adopt_statuses[:available])`

This makes it clear to the developer what status is being set

2020-11-14 00:20 UTC, hortongn commented on app/controllers/cart_controller.rb
> +    Product.where(id: session[:cart].keys).update_all(adopt_status: 0)
Again, use `Product.adopt_statuses[:available]` instead of `0`

2020-11-14 00:20 UTC, hortongn commented on app/controllers/cart_controller.rb
> +      Product.find(id).update(adopter_id: @adopter.id, adopt_status: 2, adopt_time: Time.now, dedication: session[:cart][id]['dedication'], recognition: session[:cart][id]['recognition'])
Use `Product.adopt_statuses[:pending]` instead of `2`

2020-11-14 00:20 UTC, hortongn commented on app/controllers/products_controller.rb
> +      Product.find(id).update(adopt_status: 2)
Use `Product.adopt_statuses[:pending]` instead of `2`

2020-11-16 23:50 UTC, priyakvs commented
Done the changes and have updated. Thanks Glen.

2020-11-17 16:54 UTC, hortongn approved these changes

2020-11-17 16:54 UTC, merged